### ISSUE TITLE
tree_multimap deprecated in favor of tree_map

### ISSUE THREAD

**Issue by rohan-mehta-1024** [deepmind/rlax#100]
I get this error when trying to import rlax, I think because tree_multimap has been deprecated? 

```ImportError: cannot import name 'tree_multimap' from 'jax.tree_util' (/home/rohanmehta/anaconda3/envs/py39/lib/python3.9/site-packages/jax/tree_util.py)```

**Comment by katebaumli** [comment]
Hi Rohan, are you using the latest version of rlax? This should be fixed in version 0.1.4

**Comment by rohan-mehta-1024** [comment]
Yes, I didn't realize I was using an older version. Sorry about that, and thank you :)
