### ISSUE TITLE
Relax numpy version requirement

### ISSUE THREAD

**Issue by wookayin** [deepmind/rlax#110]
1e2e4bcb4761ba6107fb565982f6cc2b951cbeb5 introduced version qualifier `numpy < 1.23` due to failing tests with jax, but I believe this has been resolved with recent jax versions and we no longer need `< 1.23`.

I could write a trivial PR that fixes requirements.txt, but let me leave it to be handled by the rlax team because the commit does not specify at which jax version tests are failing, hopefully the CL can update jax and numpy version requirements.

/cc @katebaumli

**Comment by KaleabTessera** [comment]
This would important to fix since now you can't rlax with newer versions of jax or numpy.

**Comment by katebaumli** [comment]
Apologies for the delay. This should be fixed by https://github.com/deepmind/rlax/pull/114
