### ISSUE TITLE
vtrace uses `lax.scan`? 

### ISSUE THREAD

**Issue by thisiscam** [deepmind/rlax#16]
Hi,

I'm wondering is there any fundamental reason the implementation of `vtrace` uses python for loop rather than `lax.scan`? 
The reason I ask is that it appears that currently `vtrace` compilation takes significantly longer time than a scan version, which also doesn't seem to give a huge performance benefit? 
Is backward pass memory usage the issue here?  

My scan based implementation: https://colab.research.google.com/drive/1lnxLNSse90MG8WuUu251KUMCzT0k2H4c#scrollTo=x3oxiZ9ZI5Vs

Benchmark numbers (in seconds):
```
rlax compile: 22.384824752807617
rlax: 38.763017416000366
scan compile: 0.5877189636230469
scan: 38.86183452606201
```

**Comment by mtthss** [comment]
Hello,
thanks for reaching out,

The main reason is readability,
since compilation only happens once,
we chose to go wiith the `for loop version as we received feedback that it was easier to read and modify

**Comment by thisiscam** [comment]
@mtthss I see that makes sense. Thanks!
I'm going to use my own version with scan than -- in my case since the sequence was long, and there is already an outer python loop around the vtrace, compilation takes very very long because of that.
