### ISSUE TITLE
Does discount = 0 mean "terminal" state by design?

### ISSUE THREAD

**Issue by fedetask** [deepmind/rlax#17]
I am building the code on which to base my experiments using this library. I noticed that in many `rlax` functions several episodes can seamlessly be treated as a single episode by appropriately setting zeros in the `discount` arrays. I.e. I can concatenate two episodes together
```python
# Using notation s_tm1, a_tm1, r_t, discount_t, s_t
# Let s_0, s_1, s_2, s_3, s_4, s_5 be the sequence of states of two episodes,
# where s_2 is terminal state of first episode and s_3 is the first state of the second episode
# The transition s_2 -> r_3 -> discount_3 -> s_4 is therefore "faked" with a discount = 0
values    = [v_1, v_2, v_3, v_4, v_5] 
rewards   = [r_1, r_2, 0.0, r_4, r_5]
discounts = [0.9, 0.9, 0.0, 0.9, 0.9]  # discount corresponding to s_2 -> s_3 is 0 since s_2 is terminal

targets =  n_step_bootstrapped_returns(rewards, discounts, values, n=2)
```
I checked several functions and this seems to be the case. Is this the case in all functions by design? If yes, will it continue to remain like this? I'm asking for confirmation as I might base some design choices on this very nice property of `rlax`.

Thanks for the beautiful and useful library!

**Comment by katebaumli** [comment]
Hello! Thanks for the question. Your observation is correct that this is the case in RLax.  More generally than RLax, this is the case whenever using variable (per-step) discount factors where the discount has the ability to change with the state (they are sometimes also referred to as "pcontinues" in this case (for probability of continuing) to indicate that this variable wraps up information about discount/termination). This can be read about further in [section 12.8 in "Reinforcement Learning: An Introduction" ](http://incompleteideas.net/book/RLbook2020.pdf)
