### ISSUE TITLE
Need of central documentation

### ISSUE THREAD

**Issue by EngineerKhan** [deepmind/rlax#37]
Unlike other team members of the JAX ecosystem, RLax doesn't have documentation. Is there one in progress?

**Comment by katebaumli** [comment]
Thanks for raising this! We will work on adding a central API documentation.

**Comment by EngineerKhan** [comment]
Thank you. Please keep updated in this thread once you launch any draft.

**Comment by katebaumli** [comment]
Hello, please see the [new centralized docs](https://rlax.readthedocs.io/en/latest/). 
Thanks!

**Comment by EngineerKhan** [comment]
Thank you so much, Kate! That was really quick.
