### ISSUE TITLE
Documentation and Examples

### ISSUE THREAD

**Issue by joaogui1** [deepmind/rlax#5]
So, are you guys planning on releasing the documentation and adding more examples? It's kind of hard to understand what the library has to offer and how to use it right now

**Comment by joaogui1** [comment]
Pinging @chris-chris @tomhennigan

**Comment by mtthss** [comment]
Hi, thanks for the comment.
We indeed plan to release more examples and add more extensive documentation.

**Comment by chris-chris** [comment]
@joaogui1 @mtthss 
I'm implementing more examples using rlax and haiku step by step.
currently working on A3C :)

**Comment by aslanides** [comment]
We currently have two example agents using Haiku & rlax in [bsuite](https://github.com/deepmind/bsuite) baselines.

**Comment by joaogui1** [comment]
Maybe you could copy them here or reference them in the README?

**Comment by aslanides** [comment]
See https://github.com/deepmind/bsuite/tree/master/bsuite/baselines

**Comment by joaogui1** [comment]
I had already seen it, my suggestion is more about helping other people interested in the library who won't check all repos that depend on it

**Comment by joaogui1** [comment]
I wrote this example here: [DQN](https://colab.research.google.com/drive/1JDraiOGjC5hTDwJoJAgQcS2IJuFY-r0U)
It uses the double q learning function, shows how to use vmap with your loss and implements a experience buffer. 
What do you guys think of adding it to examples?

**Comment by mtthss** [comment]
Hello @joaogui1 ,
I added to the README a link to the bsuite examples, thanks for the suggestion!

Will take a look at your proposed DQN next and get back to you tomorrow.

**Comment by mtthss** [comment]
Hello @joaogui1 ,
The DQN example would be a nice contribution!
If you put together a PR, we can discuss the details there?

**Comment by mtthss** [comment]
Thanks @joaogui1 for the contribution!

We now have fully worked online Qlearning and DQN agents, plus references in the README to several BSuite agents that use rlax.
