### ISSUE TITLE
missing library: `import optax`

### ISSUE THREAD

**Issue by jharmsen** [deepmind/rlax#8]
As of cac9c2ac8ee0122c4515ed3a487627e4af0276f4 examples [online_q_learning](https://github.com/deepmind/rlax/blame/master/examples/online_q_learning.py#L26) & [simple_dqn](https://github.com/deepmind/rlax/blame/master/examples/simple_dqn.py#L27) use non-existent `import optax`.

Changing the above lines _seems_ to fix things:
`from jax.experimental import optix as optax`

Thanks!

**Comment by mtthss** [comment]
Hello, thanks for commenting!

Optax does exist, and is a strict superset of the experimental library 'jax.experimental.optix' that you mentioned in your comment. We prefer however to use 'optax' as 'jax.experimental.optix' will be deprecated soon (as is superseeded by optax).

You can be install it with 'pip install optax',
see https://github.com/deepmind/optax.

You are right, however, that we need to update the README to list optax among the deps required for running the examples (together with BSuite and Haiku).
