### ISSUE TITLE
Title mistake in docs

### ISSUE THREAD

**Issue by HenriDeh** [deepmind/rlax#89]
Hello,

I can't PR this for you because the docs are not in this repo so I'll just open this issue.
At https://rlax.readthedocs.io/en/latest/api.html#id1, the section MPO Compute Weights and Temperature Loss appears twice, that's because the second one should be VMPO not MPO.

Best

**Comment by katebaumli** [comment]
Thanks so much for pointing this out! Fixing in https://github.com/deepmind/rlax/pull/90
